# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a285a5e13fe5841b5ab669bcc9e6168ef51f6c71945901276e080c587dc556638a0d00966976acf1816a64d8823c6b1361295081a2a3ae202f6da7b7446e75f

test:
  secret_key_base: 51924e418bd78cb3cd987526b453ba7634411836a85da8602cacc60398c89b2c91696b68d40106d381eec143744fb2ae81f4d76a638e86e4935d1a18c2299cb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
